### PR TITLE
prevent hanging when used inside tmux

### PR DESCRIPTION
**Pull request by omalled**
julia hangs when using TerminalExtensions inside tmux. This resolves the issue for me.

### CODE REVIEW

**Comment by Keno** [comment]
I wonder if the bug isn't just that we should check whether we're getting `\e[0n`, while it seems like I forgot to check for the `[`.

**Comment by omalled** [comment]
The escape sequence magic is beyond my ken -- I used a trial-and-error approach to come up with this. If there is a better fix, that would be great!

**Comment by Keno** [comment]
I fixed this in a different way. Try it out. Thanks for pointing me to what the issue was.

**Comment by omalled** [comment]
This fixes the issue with tmux. There is a new (very minor) bug though. When I use it without tmux, I get

```
~ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0


julia> n
```

where the `n` after the `julia>` prompt appears automatically without me typing `n`. The `n` doesn't appear when I launch julia from within tmux.

**Pull request closed without merging**
