### PR TITLE
fix option name Ration -> Ratio

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by simonbyrne** [comment]
I'm not sure why, but for me this still hangs when trying `Gray.(rand(10,10))`, but at least it doesn't error.

**Comment by Keno** [comment]
Yep, sorry, I half pushed a local commit ;).

**Comment by Keno** [comment]
screen shot 2018-04-13 at 5 02 23 pm

Works for me locally FWIW.

**Comment by simonbyrne** [comment]
Ah, I figured it out: I had installed images, but not an image conversion library (QuartzImageIO.jl/ImageMagick.jl) and wasn't getting a prompt. I guess it was being swallowed somewhere?

**Comment by Keno** [comment]
Maybe try the following patch:
```
@@ -88,9 +88,9 @@ module iTerm2
     for mime in iterm2_mimes
         @eval begin
             function display(d::InlineDisplay, m::MIME{Symbol($mime)}, x)
-                prepare_display_file(;filename="image",inline=true)
                 buf = IOBuffer()
                 show(Base.Base64EncodePipe(buf),m,x)
+                prepare_display_file(;filename="image",inline=true)
                 write(STDOUT, take!(buf))
                 write(STDOUT,'\a')
             end
```
?

**Comment by simonbyrne** [comment]
Yep, that gives the prompt.

**Comment by Keno** [comment]
Cool, I'll apply that patch.

**Pull request merged**
